spring.application.name=noSqlPerson
spring.graphql.graphiql.enabled=true
spring.graphql.sse.enabled=true
spring.graphql.websocket.path=/graphql

spring.graphql.cors.allowed-origins=http://localhost:5173
spring.graphql.cors.allowed-methods=GET,POST
spring.graphql.cors.allowed-headers=*